### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by mwehlou** [jorhett/learning-puppet4#2]
**Moderator note: this was a local vagrant problem unrelated to Puppet or this repository.**

Following along in the book, installing the first vagrant box in the book, it fails at vagrant up client. I'm too much of a noob to figure out what's wrong. I'm guessing it replaces the pubkey in the box, but vagrant doesn't get the private key right?

```
razr:learning-puppet4 mw(master) > vagrant up client
Bringing machine 'client' up with 'virtualbox' provider...
==> client: Importing base box 'puppetlabs/centos-7.2-64-nocm'...
==> client: Matching MAC address for NAT networking...
==> client: Checking if box 'puppetlabs/centos-7.2-64-nocm' is up to date...
==> client: Setting the name of the VM: learning-puppet4_client_1473002477474_70285
==> client: Fixed port collision for 22 => 2222. Now on port 2200.
==> client: Clearing any previously set network interfaces...
==> client: Preparing network interfaces based on configuration...
client: Adapter 1: nat
client: Adapter 2: hostonly
==> client: Forwarding ports...
client: 22 (guest) => 2200 (host) (adapter 1)
==> client: Running 'pre-boot' VM customizations...
==> client: Booting VM...
==> client: Waiting for machine to boot. This may take a few minutes...
client: SSH address: 127.0.0.1:2200
client: SSH username: vagrant
client: SSH auth method: private key
client: Warning: Remote connection disconnect. Retrying...
client: Warning: Remote connection disconnect. Retrying...
client: Warning: Remote connection disconnect. Retrying...
client:
client: Vagrant insecure key detected. Vagrant will automatically replace
client: this with a newly generated keypair for better security.
client:
client: Inserting generated public key within guest...
client: Removing insecure key from the guest if it's present...
client: Key inserted! Disconnecting and reconnecting using new SSH key...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
client: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by BMourelo** [comment]
I had the same problem.
The error message in SSH is: 
` sshd[5837]: Authentication refused: bad ownership or modes for file /home/vagrant/.ssh/authorized_keys`

Destroy the VM and then add a GUI in the Vagrantfile (  add  `vb.gui = true` after `config.vm.provider :virtualbox do |vb|` ).
Repeat the `vagrant up client` and in the GUI, login as root (password:`puppet`). 
Change the mode of `/home/vagrant/.ssh/authorized_keys` to 640. 

It works for me.

**Comment by mwehlou** [comment]
I do get the console with vb.gui = true, but there's no .ssh directory at all under /home/vagrant. There isn't any /vagrant dir either, making it hard to import keys. It seems the folder mapping isn't working. So on first blush it looks like your problem is different from mine.

It seems one needs to know too much vagrant for a beginner's guide, and this kinda stopped me in my tracks. I switched to another book instead. First one on Vagrant, then another book on puppet. Once I know more, I may revisit this. I clearly don't have the requisite Vagrant between my ears yet.

Hopefully the author fixes this since it makes following along in the book impossible unless you know enough not to need the book in the first place.

**Comment by BMourelo** [comment]
All boxes must have a vagrant user with a local home. Your initial box should be the same as mine because both was downloaded from atlas. It may have been corrupted during downloading.
You could try to destroy the VMs,  remove the directory with the Git clone, remove the box with `vagrant box remove puppetlabs/centos-7.2-64-nocm` and repeat the process.

What versions of OS, Vagrant and Virtualbox are you using ?

Also you can use  another testing environment, see in page 7.

**Comment by BMourelo** [comment]
I just saw this:
Authentication failure after inserting new key with Vagrant 1.8.5. [PATCH] #7610 https://github.com/mitchellh/vagrant/issues/7610

**Comment by mwehlou** [comment]
Benito,

Perfect! Yes, that fixed it. In summary, in file (Mac OS), for Vagrant 1.8.5:

/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/guests/linux/cap/public_key.rb

I added the following line after line 56:

```
 chmod 0600 ~/.ssh/authorized_keys
```

So that part of the file looks like this now:

```
      # Use execute (not sudo) because we want to execute this as the SSH
      # user (which is "vagrant" by default).
      comm.execute <<-EOH.sub(/^ {12}/, "")
        set -e

        if test -f ~/.ssh/authorized_keys; then
          grep -v -x -f '#{remote_path}' ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp
          mv ~/.ssh/authorized_keys.tmp ~/.ssh/authorized_keys
          chmod 0600 ~/.ssh/authorized_keys
        fi

        rm -f '#{remote_path}'
      EOH
```

**Comment by BMourelo** [comment]
Ok.
For future references:  
This has been fixed on master and will be present in the next vagrant release. 
You could work around this problem (without root access) adding to the Vagrantfile : 
>           option config.ssh.insert_key = false

**Comment by BMourelo** [comment]
Ok.

For future references:
- This has been fixed on master and will be present in the next vagrant release. 
- You could work around this problem (without root access) adding to the Vagrantfile 
( after `Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|` )

        config.ssh.insert_key = false
