### ISSUE TITLE
vagrant up client

### ISSUE THREAD

**Issue by reveal79** [jorhett/learning-puppet4#3]
When  doing vagrant up client the vagrant file stalls connecting as authentication  fails with the private key, I have tried various ways to delete the key to have it generate but still to no avail.

**Comment by andrewnaylor** [comment]
I was having the same problem until I upgraded from Vagrant 1.8 to Vagrant 1.9.1

**Comment by reveal79** [comment]
@andrewnaylor I updated Vagrant to 1.9.1 and am still having the same issue with the key this did not solve my issue.

**Comment by reveal79** [comment]
vagrant up client
Bringing machine 'client' up with 'virtualbox' provider...
==> client: Checking if box 'puppetlabs/centos-7.2-64-nocm' is up to date...
==> client: Clearing any previously set forwarded ports...
==> client: Clearing any previously set network interfaces...
==> client: Preparing network interfaces based on configuration...
    client: Adapter 1: nat
    client: Adapter 2: hostonly
==> client: Forwarding ports...
    client: 22 (guest) => 2222 (host) (adapter 1)
==> client: Running 'pre-boot' VM customizations...
==> client: Booting VM...
==> client: Waiting for machine to boot. This may take a few minutes...
    client: SSH address: 127.0.0.1:2222
    client: SSH username: vagrant
    client: SSH auth method: private key
    client: Warning: Remote connection disconnect. Retrying...
    client: Warning: Remote connection disconnect. Retrying...
    client: Warning: Remote connection disconnect. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...
    client: Warning: Authentication failure. Retrying...

reveal79@PC MINGW64 ~/linuxclass/learning-puppet4 (master)
$ vagrant --version
Vagrant 1.9.1

**Comment by reveal79** [comment]
To provide an update the login is actually root password puppet, you can then password vagrant as it wont use the insecure_key
